// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9NGJ5gowtSetOmOjNYEz1LKSl5u2Udtc',
    appId: '1:13731980005:web:452aa7c9c1d49dffac2a0c',
    messagingSenderId: '13731980005',
    projectId: 'ecommerce-80a72',
    authDomain: 'ecommerce-80a72.firebaseapp.com',
    databaseURL: 'https://ecommerce-80a72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-80a72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaozT38FuAVVoybRDq5tg1ohZ9icQUHO0',
    appId: '1:13731980005:android:ccd7c334f20a3592ac2a0c',
    messagingSenderId: '13731980005',
    projectId: 'ecommerce-80a72',
    databaseURL: 'https://ecommerce-80a72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-80a72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTf97FIK5DpAycrHtSpj0Rmr6p_R1GK8o',
    appId: '1:13731980005:ios:714350e5b3fa5dcdac2a0c',
    messagingSenderId: '13731980005',
    projectId: 'ecommerce-80a72',
    databaseURL: 'https://ecommerce-80a72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-80a72.appspot.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTf97FIK5DpAycrHtSpj0Rmr6p_R1GK8o',
    appId: '1:13731980005:ios:714350e5b3fa5dcdac2a0c',
    messagingSenderId: '13731980005',
    projectId: 'ecommerce-80a72',
    databaseURL: 'https://ecommerce-80a72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-80a72.appspot.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9NGJ5gowtSetOmOjNYEz1LKSl5u2Udtc',
    appId: '1:13731980005:web:452aa7c9c1d49dffac2a0c',
    messagingSenderId: '13731980005',
    projectId: 'ecommerce-80a72',
    authDomain: 'ecommerce-80a72.firebaseapp.com',
    databaseURL: 'https://ecommerce-80a72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-80a72.appspot.com',
  );
}
